# Generated by Django 4.2.30 on 2026-05-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripPlanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(help_text='Starting geolocation description or coordinate pair', max_length=255)),
                ('pickup_location', models.CharField(help_text='Origin freight loading terminal location', max_length=255)),
                ('dropoff_location', models.CharField(help_text='Destination freight unloading drop-off point', max_length=255)),
                ('current_cycle_used', models.FloatField(help_text='Current cumulative hours consumed within the active 70hr window')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
