# Generated by Django 4.2.30 on 2026-05-20 12:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripplanrequest',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='tripplanrequest',
            name='dropoff_location',
        ),
        migrations.RemoveField(
            model_name='tripplanrequest',
            name='pickup_location',
        ),
        migrations.AddField(
            model_name='tripplanrequest',
            name='current_coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Current physical location pin', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='tripplanrequest',
            name='dropoff_coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Destination dropoff pin', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='tripplanrequest',
            name='pickup_coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Origin load pickup pin', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='tripplanrequest',
            name='current_cycle_used',
            field=models.FloatField(default=0.0, help_text='Current cumulative hours consumed within the active 70hr window'),
        ),
    ]
